### ISSUE TITLE
Mobile login styles 

### ISSUE THREAD

**Issue by jhil** [minimill/cerberus#1]
I'll make a mockup for you.
![screenshot_2015-10-12-10-14-39](https://cloud.githubusercontent.com/assets/2228347/10433955/07d1b01c-70cb-11e5-8d06-ecdacadda0c2.png)
 But this is the current state

**Comment by jhil** [comment]
@danrschlosser didn't you complete this? confirm and close out, ya?

**Comment by schlosser** [comment]
Yup, done.
